---
title: "Log Report"
author: "Patrick"
date: "2018-01-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)

push_pull <- push_pull <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1WVgOIEIbnRDNG2AM_ZlEMjSc7w9HsA7YfhwbZ86iyKM/")
log_pp_agg <- push_pull %>%
  filter_all(any_vars(!is.na(.))) %>% 
  fill(date) %>%
  gather(excercise, count, -date) %>% 
  group_by(date, excercise) %>% 
  summarize(count = sum(count), 
            n = n())

link_weight <- gsheet::construct_download_url("https://docs.google.com/spreadsheets/d/1WVgOIEIbnRDNG2AM_ZlEMjSc7w9HsA7YfhwbZ86iyKM/", sheetid = 1356723237)
weight <- readr::read_csv(link_weight)
min_weight <- slice(weight, which.min(weight))

run_link <- gsheet::construct_download_url("https://docs.google.com/spreadsheets/d/1WVgOIEIbnRDNG2AM_ZlEMjSc7w9HsA7YfhwbZ86iyKM/", sheetid = 1870449725)

run <- readr::read_csv(run_link, 
                       col_type = readr::cols(
                         date = col_date(format = ""),
                         distance = col_double(),
                         time = col_character(),
                         pace = col_character())) %>% 
  mutate(time = hms::parse_hms(paste0("00:",gsub(":00", "", time))), 
         pace = hms::parse_hms(paste0("00:",pace)))

aim <- data_frame(date = seq.Date(as.Date("2017-12-27"), 
                                  as.Date("2018-01-25"), 
                                  by = "days"), 
                  pull = 6 + as.integer(date - first(date)) * 2, 
                  push = 30 + as.integer(date - first(date)) * 5) %>% 
  gather(excercise, aim, -date) %>% 
  left_join(., log_pp_agg, by = c("excercise", "date")) %>% 
  mutate(check = count >= aim)



```

```{r push_pull_plot, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(aim, aes(date)) + 
  geom_point(aes(y = count)) + 
  geom_text(aes(y = 95, label = count)) + 
  geom_text(aes(y = 85, label = aim), color = "red") +
  geom_line(aes(y = aim), color = "red") + 
  geom_rect(aes(xmin = date - 0.5, xmax = date + 0.5, ymin = -Inf, ymax = Inf, fill = check), alpha = 0.2) + 
  facet_wrap(~excercise, ncol = 1, scales = "free_y") + 
  labs(x = NULL, y = NULL) + 
  scale_y_continuous(breaks = seq(0, 100, by = 10), limits = c(0, NA)) + 
  scale_x_date(breaks = seq.Date(as.Date("2017-12-27"), 
                                 as.Date("2018-01-25"), 
                                 by = "days")) + 
  scale_fill_manual(values = c("TRUE" = "green", "FALSE" = "red", "NA" = "grey")) + 
  theme_light() +
  theme(panel.grid = element_blank(), 
        panel.grid.major.y = element_line(size = 0.1), 
        axis.text.x = element_text(angle = 90), 
        legend.position = "none")
```

```{r, echo = FALSE, warning = FALSE, message=FALSE}
library(viridis)
library(ggthemes)

df_dates <- data_frame(date = seq.Date(as.Date("2017-01-01"), as.Date("2018-12-31"), by = "days"))
pull <- filter(log_pp_agg, excercise == "pull") %>% 
  left_join(df_dates, .) %>% 
  mutate(year = format(date, "%Y"),
         week = as.integer(format(date, "%W")),
         day = factor(weekdays(date, TRUE), 
                      levels = rev(c("Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"))))



ggplot(left_join(df_dates, pull), aes(x = week, y = day, fill = count)) + 
  geom_tile(color = "white", size = 0.5) + 
  scale_fill_viridis(name = "Count", 
                     option = "D", 
                     direction = -1, 
                     na.value = "grey93", 
                     limits = c(0, 100)) + 
  facet_wrap("year", ncol = 1) +
  scale_x_continuous(
    expand = c(0, 0), 
    breaks = seq(1, 52, length = 12), 
    labels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", 
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")) + 
  theme_tufte() + 
  theme(axis.title = element_blank(), 
        axis.ticks = element_blank(), 
        legend.position = "bottom", 
        legend.key.width = unit(1, "cm"), 
        strip.text = element_text(hjust = 0.01, face = "bold", size = 12)) +
  ggtitle("PULL UP!")
```


```{r weight_plot, echo=FALSE}
weight %>% 
  ggplot(aes(date, weight)) +
  geom_point() + 
  geom_point(data = min_weight, col = "blue", size = 3) +
  geom_hline(data = min_weight, aes(yintercept = weight)) + 
  geom_text(data = min_weight, aes(y = weight + 10, label = weight)) +
  lims(y = c(0, 120)) + 
  theme_light() + 
  theme(panel.grid = element_blank()) + 
  labs(title = "Weight", 
       x = NULL, y = NULL) 
```
```{r, echo=FALSE}
ggplot(run, aes(date, distance)) + 
  geom_col() +
  theme_light() +
  labs(title = "Running", x = NULL, y = NULL)
```

